language: bash
sudo: required
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install build-essential
  - sudo apt-get install aptitude
  - sudo apt-get install libstdc++6
  - sudo apt-get install -y 
        gcc-4.9
        g++-4.8
        git
        python2.7
        nodejs
        cmake
        default-jre
        wget

  - sudo apt-get upgrade libstdc++6
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
install:
  # Get the emsdk repo
  - git clone https://github.com/juj/emsdk.git
  # Enter that directory
  - cd emsdk
 
  # Fetch the latest version of the emsdk (not needed the first time you clone)
  - git pull
  # Download and install the latest SDK tools.
  - ./emsdk install latest
  # Make the "latest" SDK "active" for the current user. (writes ~/.emscripten file)
  - ./emsdk activate latest
  # Activate PATH and other environment variables in the current terminal
  - source ./emsdk_env.sh

  # SWI-Prolog depends on zlib. To compile it to WebAssembly:  
  - wget https://zlib.net/zlib-1.2.11.tar.gz -O "$HOME/zlib-1.2.11.tar.gz"
  - tar -xf "$HOME/zlib-1.2.11.tar.gz" -C "$HOME"
  - cd "$HOME/zlib-1.2.11"
  - emconfigure ./configure
  - emmake make
  # Build SWI-Prolog
  - git clone https://github.com/rla/swipl-devel.git "$HOME/swipl-devel"
  - cd "$HOME/swipl-devel"
  - git fetch
  - git checkout wasm
  - echo n3 | sudo ./prepare
  # After this we can run configure and compile:
  - cd "$HOME/swipl-devel/src"
  - LDFLAGS=-L"$HOME/zlib-1.2.11"
    LIBS=-lzlib
    CPPFLAGS=-I"$HOME/zlib-1.2.11"
    COFLAGS=-O3 emconfigure ./configure
      --disable-mt
      --disable-gmp
      --disable-custom-flags
    emmake make  
script:
  - ls
